name: TCDD Kontrol

on:
  schedule:
    - cron: '*/5 * * * *'   # her 15 dakikada bir
  workflow_dispatch:           # elle de çalıştırabilirsin

jobs:
  kontrol:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python tcdd_checker.py
